font_12: &font_12 ${font_family}:pixelsize=${font_size_12}
font_13: &font_13 ${font_family}:pixelsize=${font_size_13}
font_14: &font_14 ${font_family}:pixelsize=${font_size_14}
font_15: &font_15 ${font_family}:pixelsize=${font_size_15}
font_14_bold: &font_14_bold ${font_family}:pixelsize=${font_size_14}:weight=bold
underline: &underline { deco: { underline: { size: 1, color: "${color_main}" } } }

bar:
  monitor: ${output}
  layer: top
  location: bottom
  height: ${height}
  spacing: ${spacing}
  margin: 0
  font: *font_15
  foreground: ${color_main}
  background: 00000000

  left:
    - pipewire:
        anchors:
          volume_icon: &volume_icon
            map:
              conditions:
                form_factor == headphones && description != "CalDigit Pro Audio Stereo" && ~muted:
                  string: { text: 󰋋 }
                form_factor == headphones && description != "CalDigit Pro Audio Stereo" && muted:
                  string: { text: 󰟎 }
                ~muted:
                  string: { text: 󰕾 }
                muted:
                  string: { text: 󰖁 }
        content:
          map:
            on-click:
              left: volume mute
              wheel-up: volume up
              wheel-down: volume down
            conditions:
              type == sink && muted:
                list:
                  foreground: "${color_red}"
                  items:
                    - string: { text: " " }
                    - *volume_icon
                    - string: { text: "{cubic_volume:3}%", left-margin: "${margin_icon}" }
              type == sink && ~muted:
                list:
                  foreground: "${color_main_bright}"
                  items:
                    - string: { text: " " }
                    - *volume_icon
                    - string: { text: "{cubic_volume:3}%", left-margin: "${margin_icon}" }

    - backlight:
        name: intel_backlight
        foreground: ${color_main_bright}
        content:
          list:
            on-click:
              left: rofi-night-light
              wheel-up: brightness up
              wheel-down: brightness down
            items:
              - string: { text: 󰃠 }
              - string: { text: "{percent:3}%", left-margin: "${margin_icon}" }

    - battery:
        name: BAT0
        poll-interval: 30000
        anchors:
          battery_icon: &battery_icon
            map:
              conditions:
                state == charging || state == full:
                  string: { text:  }
                state != charging:
                  ramp:
                    tag: capacity
                    items:
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
                      - string: { text:  }
        content:
          map:
            conditions:
              state != charging && capacity <= 20:
                list:
                  foreground: "${color_red}"
                  items:
                    - *battery_icon
                    - string: { text: "{capacity:3}%", left-margin: "${margin_icon}" }
              state == charging || capacity > 20:
                - *battery_icon
                - string: { text: "{capacity:3}%", left-margin: "${margin_icon}" }

    - network:
        poll-interval: 10000
        content:
          map:
            conditions:
              name == wlan0 && state == up:
                - ramp:
                    tag: quality
                    items:
                      - string: { text: 󰢿 }
                      - string: { text: 󰢼 }
                      - string: { text: 󰢼 }
                      - string: { text: 󰢽 }
                      - string: { text: 󰢽 }
                      - string: { text: 󰢾 }
                - string: { text: "{quality:3}%", left-margin: "${margin_icon}", right-margin: "${double_spacing}" }
              name == wlan0 && state != up:
                list:
                  foreground: "${color_red}"
                  items:
                    - string: { text: 󰢿 }
                    - string: { text: "{quality:3}%", left-margin: "${margin_icon}", right-margin: "${double_spacing}" }
              carrier && state == up:
                - string: { text: "󰈀 100%", right-margin: "${double_spacing}" }

  center:
    - niri-workspaces:
        font: *font_12
        foreground: ${color_main_bright}
        content:
          map:
            on-click: niri msg action focus-workspace {id}
            conditions:
              active:
                string: { text: , margin: "${margin_icon_workspaces}" }
              empty:
                empty: {}
              ~active:
                string: { text: , margin: "${margin_icon_workspaces}" }

  right:
    - script:
        path: ~/scripts/yambar-screen-capture
        args:
          - ${output}
        font: *font_14
        content:
          map:
            on-click: screen-capture
            conditions:
              recording:
                string: { text: , foreground: "${color_red}" }

    - removables:
        content:
          map:
            conditions:
              ~mounted:
                string:
                  on-click:
                    left: udisksctl mount -b {device}
                    right: udisksctl power-off -b {device}
                  text: 󱊞
              mounted:
                string:
                  on-click:
                    left: udisksctl unmount -b {device}
                    right: sh -c "udisksctl unmount -b {device} && udisksctl power-off -b {device}"
                  text: 󱊞
                  foreground: ${color_main_bright}
                  <<: *underline

    - script:
        path: ~/scripts/yambar-vpn
        font: *font_14_bold
        content:
          map:
            on-click: vpn
            conditions:
              connected:
                string: { text: VPN, foreground: "${color_main_bright}", <<: *underline }
              ~connected:
                string: { text: VPN }

    - label:
        font: *font_13
        content:
          string:
            on-click:
              left: rofi-power
              right: sh -c "ROFI_RETV=1 rofi-power 'in 60 minutes'"
            text: 

    - clock:
        time-format: "%d.%m.%Y. %H:%M "
        foreground: ${color_main_bright}
        content:
          - string:
              on-click: toggle "foot --app-id=calendar khal interactive"
              text: "{time}"
