#!/usr/bin/env python

# regenerate .gitignore
# ignore everything except tracked files; for better editor support

import subprocess

output = subprocess.run(["git", "ls-files"], stdout=subprocess.PIPE)
output = output.stdout.decode("utf-8")

files = output.splitlines()
folders = []

for file in files:
   parents = file.split("/")[:-1]
   for i in range(1, len(parents)):
      parents[i] = f"{parents[i - 1]}/{parents[i]}"

   for i, path in enumerate(parents):
      if i >= len(folders):
         folders.append(set())
      folders[i].add(path)

gitignore = "*\n"
for paths in folders:
   paths = sorted(paths)
   for path in paths:
      gitignore += f"!{path}\n{path}/*\n"
for path in files:
   gitignore += f"!{path}\n"

with open(".gitignore", "w") as file:
   file.write(gitignore)
