#!/bin/bash

sway-audio-idle-inhibit --dry-print-sink |
while read -r status; do
   if [[ $last_status == $status ]]; then
      continue
   fi
   last_status="$status"
   pids="$(pgrep -d , -f "systemd-inhibit --who=audio")"
   if [[ $status == "RUNNING" && -z $pids ]]; then
      systemd-inhibit --who=audio --what=idle sleep infinity &> /dev/null &
   fi
   if [[ $status == "NOT RUNNING" && -n $pids ]]; then
      pkill -P "$pids" sleep
   fi
done
