#!/bin/bash

# brightness       - get current brightness
# brightness up    - turn up brightness by 10%
# brightness down  - turn down brightness by 10%

path="/sys/class/backlight/intel_backlight"
max=$(cat "$path/max_brightness")
brightness=$(cat "$path/brightness")
brightness=$((((brightness * 100 + max - 1) / max)))
step=10

if [[ -z "$1" ]]; then
   echo "$brightness"
   exit
fi

if [[ "$1" == "up" ]]; then
   brightness=$(((brightness + step + 5) / 10 * 10))
   brightness=$((brightness < 100 ? brightness : 100))
   notify-send "Brightness" -h int:value:"$brightness" -h string:x-dunst-stack-tag:progress
   brightness=$(((brightness * max) / 100))
   echo "$brightness" > "$path/brightness"
   exit
fi

if [[ "$1" == "down" ]]; then
   brightness=$(((brightness - step + 5) / 10 * 10))
   notify-send "Brightness" -h int:value:"$brightness" -h string:x-dunst-stack-tag:progress
   brightness=$((brightness > 1 ? brightness : 1))
   brightness=$(((brightness * max) / 100))
   echo "$brightness" > "$path/brightness"
   exit
fi

echo "Expected 'brightness [up|down]'" >&2
exit 1
