#!/bin/dash

# brightness                    - get current brightness
# brightness up   [--silent]    - turn up brightness by 10%
# brightness down [--silent]    - turn down brightness by 10%
# brightness <n>  [--silent]    - set brightness to wanted %
# brightness detect-buses       - detect external monitors

dir="$HOME/.local/state/brightness"
config="$dir/external-monitor-buses"
backlight="$dir/backlight"

get_brightness() {
   if command -v backlight_control > /dev/null; then
      backlight_control
   elif [ -s "$backlight" ]; then
      cat "$backlight"
   else
      echo 0
   fi
}

set_brightness() {
   if command -v backlight_control > /dev/null; then
      brightness="$(backlight_control "$1")"
   else
      brightness=0
      if [ -s "$backlight" ]; then
         brightness="$(cat "$backlight")"
      fi
      case "$1" in
         +*) brightness=$((brightness + ${1#+}));;
         -*) brightness=$((brightness - ${1#-}));;
         *)  brightness=$1;;
      esac
      if [ "$brightness" -lt 0 ]; then
         brightness=0;
      elif [ "$brightness" -gt 100 ]; then
         brightness=100;
      fi
      mkdir -p "$dir"
      echo "$brightness" > "$backlight"
   fi

   yambar-signal brightness refresh

   if [ "$2" != "--silent" ]; then
      notify-send "Brightness $brightness%" -a osd -h "int:value:$brightness" -h string:x-canonical-private-synchronous:osd
   fi

   if [ ! -s "$config" ]; then
      return
   fi

   # debounce ddcutil calls
   sleep 0.25
   count="$(pgrep -xc brightness)"
   if [ "$count" -gt 1 ]; then
      exit
   fi
   while read -r output bus; do
      ddcutil --bus "$bus" setvcp 10 "$brightness" &
   done < "$config"
}

if [ -z "$1" ]; then
   get_brightness
   exit
fi

if [ "$1" = "up" ]; then
   set_brightness +10 "$2" &
   exit
fi

if [ "$1" = "down" ]; then
   set_brightness -10 "$2" &
   exit
fi

if [ "$1" -eq "$1" ] 2> /dev/null; then
   set_brightness "$1" "$2" &
   exit
fi

if [ "$1" = "detect-buses" ]; then
   mkdir -p "$dir"
   echo -n "" > "$config"
   ddcutil detect --brief 2> /dev/null | grep -A2 "^Display " | grep -v "^Display " | grep -v "^--" | while read -r line; do
      bus="${line#*-}"
      read -r line
      output="${line#*-}"
      echo "$output $bus" >> "$config"
      ddcutil --bus "$bus" setvcp 10 "$(brightness)" &
   done
   exit
fi

echo "Expected 'brightness [up|down|<n>|detect-buses]'" >&2
exit 1
