#!/bin/bash

# brightness       - get current brightness
# brightness up    - turn up brightness by 10%
# brightness down  - turn down brightness by 10%

step=10
brightness=$(lux -G)
brightness=${brightness:0:-1}

if [[ -z "$1" ]]; then
   echo "$brightness"
   exit 0
fi

if [[ "$1" == "up" ]]; then
   brightness=$(((brightness + step + 5) / 10 * 10))
   brightness=$((brightness < 100 ? brightness : 100))
   lux -S "$brightness%" > /dev/null
elif [[ "$1" == "down" ]]; then
   brightness=$(((brightness - step + 5) / 10 * 10))
   brightness=$((brightness > 10 ? brightness : 10))
   lux -S "$brightness%" > /dev/null
else
   echo "Expected 'brightness [up|down]'" >&2
   exit 1
fi
