#!/bin/dash

if niri msg outputs | grep -q "Philips Consumer Electronics Company Philips FTV 0x01010101"; then
   if ! pactl list modules | grep -q module-alsa-sink; then
      pactl load-module module-alsa-sink device=hw:0,3
      pactl set-default-sink alsa_output.hw:0,3
   fi
else
   if pactl list modules | grep -q module-alsa-sink; then
      wpctl clear-default      # pactl set-default-sink @NONE@ won't work?
      pactl unload-module module-alsa-sink
   fi
fi
