#!/bin/bash

# i3-focus-or-open --class <class> <command>                  - focus window matched by class, or exec command if none matched
# i3-focus-or-open --workspace <ws> <command>                 - focus window matched by workspace, or exec command if none matched
# i3-focus-or-open --workspace <ws> --class <class> <command> - focus window matched by class and workspace, or exec command if none matched

args=()
while [[ $# -gt 0 ]]; do
   case "$1" in
      --workspace) workspace=$2; shift; shift;;
      --class)     class=$2;     shift; shift;;
      *)           args+=("$1"); shift;;
   esac
done
set -- "${args[@]}"

if [[ ${#args[@]} -ne 1 ]]; then
   echo "Exactly one positional parameter expected" >&2
   exit 1
elif [[ -z $workspace && -z $class ]]; then
   echo "Expected --workspace or --class" >&2
   exit 1
fi

command=$1
criteria=""

if [[ -n $class ]]; then
   criteria+="class=^$class$"
fi
if [[ -n $criteria ]]; then
   criteria="[$criteria]"
fi

exists=$(i3-msg "$criteria focus" 2>/dev/null | jq ".[].success")
if [[ $exists == "false" ]]; then
   i3-msg workspace "$workspace"
   i3-msg exec "$command"
fi
