#!/bin/bash

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

if [[ $status != "Discharging" ]]; then
   icon=$icon_charging
elif [[ $capacity -gt 88 ]]; then
   icon=$icon_100
elif [[ $capacity -gt 62 ]]; then
   icon=$icon_75
elif [[ $capacity -gt 37 ]]; then
   icon=$icon_50
elif [[ $capacity -gt 12 ]]; then
   icon=$icon_25
else
   icon=$icon_0
fi

if [[ $capacity -lt 20 ]]; then
   low=true
fi

capacity=$(printf "%4s" "$capacity%")

echo "$icon $capacity"
if [[ $low == true && $icon != $icon_charging ]]; then
   echo "$icon $capacity"
   echo "$color_red"
fi
