#!/bin/bash

if [[ $button -eq 1 ]]; then
   volume mute
elif [[ $button -eq 3 ]]; then
   kitty alsamixer
elif [[ $button -eq 4 ]]; then
   volume up
elif [[ $button -eq 5 ]]; then
   volume down
fi

vol=$(volume)
vol=$(((vol + 5) / 10 * 10))
vol=$(printf "%4s" "$vol%")

headphones=$((amixer get Headphone | grep -q "\[on\]") && echo true || echo false)
muted=$(volume muted && echo true || echo false)

if [[ $headphones == true ]]; then
   icon="$icon_headphones"
elif [[ $muted == true ]]; then
   icon="$icon_muted"
fi

echo "$icon $vol"

if [[ $muted == true ]]; then
   echo "$icon $vol"
   echo "$color_red"
fi
