#!/bin/bash

# night-light            - toggle night light
# night-light --enabled  - check if night light is on

temperature=$(xsct | awk '{ print $5 }')

if [[ $1 == "--enabled" ]]; then
   if [[ $temperature -eq 3400 ]]; then
      exit 0
   else
      exit 1
   fi
fi

if [[ $temperature -ne 3400 ]]; then
   xsct 3400
else
   xsct 0
fi
