#!/bin/dash

# night-light on      - enable night light
# night-light off     - disable night light
# night-light auto    - automatically enable/disable night light

if [ "$1" = "on" ] && ! pgrep -f "wlsunset -S 00:00 -s 00:00" > /dev/null; then
   pkill wlsunset
   wlsunset -S 00:00 -s 00:00 > /dev/null 2>&1 &
fi
if [ "$1" = "off" ]; then
   pkill wlsunset
fi
if [ "$1" = "auto" ] && ! pgrep -f "wlsunset -l 45.8 -L 16.0" > /dev/null; then
   pkill wlsunset
   wlsunset -l 45.8 -L 16.0 > /dev/null 2>&1 &
fi
