#!/bin/dash

niri msg --json focused-window | jq -c -r '.id,.is_floating,.layout.window_size[0],.layout.window_size[1]' | {
   read id
   read floating
   read window_width
   read window_height

   path="/tmp/niri-float-$id"
   niri msg action toggle-window-floating

   # floating a window for the first time - center it
   if [ "$floating" = "false" ] && [ ! -f "$path" ]; then
      niri msg --json focused-output | jq .logical.width,.logical.height | {
         read width
         read height
         niri msg action set-window-width 50%
         niri msg action set-window-height 50%
         niri msg action move-floating-window -x "$((width / 4))" -y "$((height / 4))"
      }
   fi

   # floating a window - store tiling size
   if [ "$floating" = "false" ]; then
      echo -n "$window_width $window_height" > "$path"
   fi

   # unfloating a window - restore last known tiling size
   if [ "$floating" = "true" ] && [ -f "$path" ]; then
      read width height < "$path"
      niri msg action set-window-width "$width"
      niri msg action set-window-height "$height"
   fi
}
