#!/bin/dash

if [ -z "$1" ]; then
   echo "Expected 'play-sound <sound>'" >&2
   exit 1
fi

path="$HOME/sounds/$1.mp3"

if [ ! -f "$path" ]; then
   echo "Sound file does not exist" >&2
   exit 1
fi

paplay "$path" >/dev/null 2>&1 &
