#!/bin/bash

if [[ -z $ROFI_RETV ]]; then
   rofi -show powermenu -modes powermenu:"$0"
   exit
fi

echo -e "\0prompt\x1fPower"
echo -e "\0no-custom\x1ftrue"
echo -e "\0keep-selection\x1ffalse"

shutdown_timer=" Shutdown Timer"
shutdown=" Shutdown"
soft_restart=" Soft Restart"
hard_restart=" Hard Restart"
sleep="󰒲 Sleep"
# lock=" Lock"

if [[ -z $1 || $1 == "" ]]; then
   echo "$shutdown_timer"
   echo "$shutdown"
   echo "$soft_restart"
   echo "$hard_restart"
   echo "$sleep"
   # echo "$lock"
   exit 1
fi

case "$1" in
   # $lock)
   #    screen-lock
   # ;;
   $sleep)
      systemctl suspend
   ;;
   $hard_restart)
      systemctl reboot
   ;;
   $soft_restart)
      systemctl soft-reboot
   ;;
   $shutdown)
      systemctl poweroff
   ;;
   $shutdown_timer)
      echo ""
      echo "in 60 minutes"
      echo "in 90 minutes"
      echo "in 120 minutes"
      echo "at 00:00"
      echo "at 01:00"
      echo "at 02:00"
      if ! [[ -f /run/systemd/shutdown/scheduled ]]; then
         echo "at 03:00"
      else
         echo "Cancel shutdown"
      fi
   ;;
   "in 60 minutes") ;&
   "in 90 minutes") ;&
   "in 120 minutes")
      minutes=${1:3:-8}
      shutdown --poweroff +$minutes
      coproc systemd-inhibit --who=power --what=idle sleep infinity
      notify-send -h string:x-dunst-stack-tag:shutdown " Shutdown scheduled for $(date -d '+'$minutes' minutes' '+%0l:%M')"
   ;;
   "at 00:00") ;&
   "at 01:00") ;&
   "at 02:00") ;&
   "at 03:00")
      time=${1:3}
      shutdown --poweroff $time
      coproc systemd-inhibit --who=power --what=idle sleep infinity
      notify-send -h string:x-dunst-stack-tag:shutdown " Shutdown scheduled for $time"
   ;;
   "Cancel shutdown")
      shutdown -c
      pkill -P $(pgrep -d , -f "systemd-inhibit --who=power") sleep
      notify-send -h string:x-dunst-stack-tag:shutdown " Shutdown cancelled"
esac
