#!/bin/bash

# screen-capture                - start or stop a screen recording and save it to $XDG_VIDEOS_DIR/screencasts
# screen-capture --selection    - select part of screen
# screen-capture --audio        - record sound too

set -e

while [[ $# -gt 0 ]]; do
   case "$1" in
      --selection) selection=true;;
      --audio)     audio=true;;
      *)
         echo "Expected 'screen-capture [--selection] [--audio]'" >&2
         exit 1
      ;;
   esac
   shift
done

if pkill -SIGINT wf-recorder; then
   yambar-signal screen-capture off
   exit 0
fi

args=()

dir="$XDG_VIDEOS_DIR/screencasts"
file="$dir/$(date +'%F %T:%N' | cut -c 1-25).mp4"
args+=("--file=$file")

if [[ $audio == true ]]; then
   audio="$(wpctl inspect @DEFAULT_SINK@ | grep 'node.name' | awk '{print $4}')"
   audio="${audio:1:-1}.monitor"
   args+=("--audio=$audio")
fi

if [[ $selection == true ]]; then
   args+=("--geometry=$(slurp)")
fi

output="$(niri msg focused-output | grep Output | awk -F '[()]' '{print $2}')"
args=("--output=$output" "${args[@]}")

mkdir -p "$dir"
wf-recorder "${args[@]}" &
yambar-signal "screen-capture $output" on
