#!/bin/bash

initial=$(cat "$HOME/.local/share/screen-layout/last-run")
command="$initial"
counter=0

while [[ $counter -lt 10 && $command == $initial ]]; do
   sleep 0.1
   "$HOME/scripts/screen-layout" --restore
   command=$(cat "$HOME/.local/share/screen-layout/last-run")
   ((counter++))
done
