#!/bin/dash

# volume         - get current volume
# volume up      - turn up volume by 10%
# volume down    - turn down volume by 10%
# volume <n>     - set volume to wanted %
# volume mute    - toggle mute

get_volume() {
   wpctl get-volume @DEFAULT_SINK@ | awk '{printf $2*100}'
}

if [ -z "$1" ]; then
   get_volume
   echo ""
   exit
fi

if [ "$1" = "up" ]; then
   wpctl set-volume -l 1.0 @DEFAULT_SINK@ 10%+
   notify-send "Volume" -h string:x-dunst-stack-tag:progress -h "int:value:$(get_volume)"
   exit
fi

if [ "$1" = "down" ]; then
   wpctl set-volume -l 1.0 @DEFAULT_SINK@ 10%-
   notify-send "Volume" -h string:x-dunst-stack-tag:progress -h "int:value:$(get_volume)"
   exit
fi

if [ "$1" -eq "$1" ] 2> /dev/null; then
   wpctl set-volume -l 1.0 @DEFAULT_SINK@ "$1%"
   notify-send "Volume" -h string:x-dunst-stack-tag:progress -h "int:value:$1"
   exit
fi

if [ "$1" = "mute" ]; then
   wpctl set-mute @DEFAULT_SINK@ toggle
   exit
fi

echo "Expected 'volume [up|down|<n>|mute]'" >&2
exit 1
