#!/bin/bash

set -e

if ! pgrep openvpn > /dev/null; then
   sudo --askpass openvpn --cd /etc/openvpn/client/ --config default.ovpn --daemon > /dev/null
   yambar-refresh vpn
   notify-send "VPN connected"

   # external death
   tail --pid="$(pidof openvpn)" -f /dev/null
   yambar-refresh vpn
   notify-send "VPN connection lost"
else
   sudo --askpass pkill -x openvpn
   pgrep -f "${BASH_SOURCE[0]}" | grep -v $$ | ifne xargs kill -9
   yambar-refresh vpn
   notify-send "VPN disconnected"
fi
