#!/bin/bash

# yambar-vpn daemon - due to yambar's limitations
# yambar-vpn click  - enable/disable vpn

if [[ $1 == "click" ]]; then
   vpn
   exit
fi

if [[ $1 == "daemon" ]]; then
   function update {
      if pidof openvpn; then
         echo -e "connected|bool|true\n"
      else
         echo -e "connected|bool|false\n"
      fi
   }

   update
   trap update USR1
   while :; do
      sleep infinity &
      pid="$!"
      wait $pid
      kill $pid
   done
   exit
fi
