#!/bin/bash

if [[ $# -ne 2 ]]; then
   exit
fi

if [[ $2 == "on" ]]; then
   pgrep -f "yambar-$1" | xargs -r kill -USR1
fi

if [[ $2 == "off" ]]; then
   pgrep -f "yambar-$1" | xargs -r kill -USR2
fi
