#!/bin/dash

# yambar-toggle              - toggle bar on all outputs
# yambar-toggle --refresh    - reflect current state on all outputs

if [ "$1" = "--refresh" ] && ! pidof yambar > /dev/null; then
   exit
fi

if [ "$1" != "--refresh" ] && pidof yambar > /dev/null; then
   sed -i "s/ bottom/ \/\/ bottom/g" ~/.config/niri/config.kdl
   pkill yambar > /dev/null 2>&1
   exit
fi

sed -i "s/\/\/ bottom/\bottom/g" ~/.config/niri/config.kdl

# spawn yambar on all outputs
niri msg --json outputs | jq -r '.[] | select(.current_mode) | "\(.name) \(.logical.scale)"' > /tmp/yambar-outputs
while read -r output scale; do
   pidfile="$XDG_RUNTIME_DIR/yambar-$output.pid"
   if [ -s $pidfile ]; then
      continue
   fi
   OUTPUT="$output"
   SCALE="$scale"
   . "$XDG_CONFIG_HOME/yambar/config.env"
   yambar --print-pid="$pidfile" &
done < /tmp/yambar-outputs

# destroy on disconnected outputs
for pidfile in "$XDG_RUNTIME_DIR/yambar-"*; do
   if [ ! -s "$pidfile" ]; then
      continue
   fi
   output="$(basename "$pidfile" | sed 's/^yambar-//' | sed 's/\.pid$//')"
   if ! grep -q "^$output " /tmp/yambar-outputs; then
      kill -TERM "$(cat $pidfile)" 2>/dev/null
      rm "$pidfile"
   fi
done

rm /tmp/yambar-outputs
