#!/bin/bash

function enable {
   echo -e "connected|bool|true\n"
}

function disable {
   echo -e "connected|bool|false\n"
}

if ip link show tun0 | grep ",UP," > /dev/null; then
   enable
else
   disable
fi

trap enable USR1
trap disable USR2

while :; do
   sleep infinity &
   pid="$!"
   wait $pid
   kill $pid
done
