#!/bin/bash

function enable {
   echo -e "recording|bool|true\n"
}

function disable {
   echo -e "recording|bool|false\n"
}

if pgrep -f "wf-recorder --output=$1" > /dev/null; then
   enable
else
   disable
fi

trap enable USR1
trap disable USR2

while :; do
   sleep infinity &
   pid="$!"
   wait $pid
   kill $pid
done
